services:
  api: &api
    image: "alpha-apartments-api:${BUILD_ENVIRONMENT}-${BUILD_VERSION}"
    container_name: alpha-api
    hostname: api
    restart: always
    healthcheck:
        test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8000/"
        start_period: 60s
        interval: 60s
        timeout: 10s
        retries: 10
    volumes:
      - .:/app:z
      - ./docker/run-data/staticfiles:/app/staticfiles:z
    # ports:
    #   - "8000:8000"
    expose:
     - "8000"
    env_file:
      - "./docker/env/.env.${BUILD_ENVIRONMENT}"
    depends_on:
      - db
      - mailpit
    command: /start
    networks:
      - alpha_apartments_production_network

  db:
    image: "alpha-postgres-db:${BUILD_ENVIRONMENT}-${BUILD_VERSION}"
    restart: always
    healthcheck:
      # Using -d ensures it looks for the specific DB you created
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost -p 5433"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s  # Important: Allows DB to finish boot before failing
    container_name: db
    ports:
      - "5433:5433"
    volumes:
      - ./docker/run-data/db:/var/lib/postgresql/data
    env_file:
      - "./docker/env/.env.${BUILD_ENVIRONMENT}"
    networks:
      - alpha_apartments_production_network

  # good for local development, prod should use Mailgun
  mailpit:
    image: "alpha-mailpit:${BUILD_ENVIRONMENT}-${BUILD_VERSION}"
    restart: unless-stopped
    container_name: mailpit
    healthcheck:
      test: curl http://localhost:8025/readyz -I || exit 1
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - ./docker/run-data/alpha_apartments_mailpit_data:/data
    env_file:
      - "./docker/env/.env.${BUILD_ENVIRONMENT}"
    networks:
      - alpha_apartments_production_network

  client:
    container_name: alpha-client
    hostname: client
    image: alpha-client:${BUILD_ENVIRONMENT}-${BUILD_VERSION}
    # ports:
    #   - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s # Allows extra time for Next.js to compile/start in dev mode
    expose:
      - "3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - nextjs_cache:/app/.next
    networks:
      - alpha_apartments_production_network

  nginx:
    image: alpha-nginx:${BUILD_ENVIRONMENT}-${BUILD_VERSION}
    restart: always
    container_name: alpha-nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
     - "8080:80"
    volumes:
     - ./staticfiles:/app/staticfiles
     - logs_store:/var/log/nginx
    depends_on:
     - api
    networks:
      - alpha_apartments_production_network

networks:
  alpha_apartments_production_network:
    external: true

volumes:
  alpha_apartments_db_data: {}
  alpha_apartments_mailpit_data: {}
  logs_store: {}
  nextjs_cache: {}
